version: '3'
services:
  web:
    build: ./app
    volumes: 
      - "./app:/usr/src/app"
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: flask_db
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: flask_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    links:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
